sudo: false
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8-dev
    env: TOXENV=py38
install:
- pip install tox codecov twine
script:
- tox -e $TOXENV
after_success:
- codecov
